In [17]:
import numpy as np
import pandas as pd

In [18]:
# 1
df = pd.read_csv('Dataset_pandas.csv')
df.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.121478,tcp,-,FIN,6,4,258,172,74.087490,14158.9420,...,0,0,1,1,0,0,0,0,Normal,0
1,0.649902,tcp,-,FIN,14,38,734,42014,78.473370,8395.1120,...,0,0,1,1,0,0,0,0,Normal,0
2,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,1572.2719,...,0,0,1,1,0,0,0,0,Normal,0
3,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,2740.1790,...,0,0,1,1,1,1,0,0,Normal,0
4,0.449454,tcp,-,FIN,10,6,534,268,33.373825,8561.4990,...,0,0,2,1,0,0,0,0,Normal,0

In [19]:
df.shape

(175341, 36)

In [20]:
# 2
df.columns

Index(['dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt',
       'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt',
       'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_src_dport_ltm', 'ct_dst_sport_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'is_sm_ips_ports',
       'attack_cat', 'label'],
      dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175341 entries, 0 to 175340
Data columns (total 36 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   dur                175341 non-null  float64
 1   proto              175341 non-null  object
 2   service            175341 non-null  object
 3   state              175341 non-null  object
 4   spkts              175341 non-null  int64
 5   dpkts              175341 non-null  int64
 6   sbytes             175341 non-null  int64
 7   dbytes             175341 non-null  int64
 8   rate               175341 non-null  float64
 9   sload              175341 non-null  float64
 10  dload              175341 non-null  float64
 11  sloss              175341 non-null  int64
 12  dloss              175341 non-null  int64
 13  sinpkt             175341 non-null  float64
 14  dinpkt             175341 non-null  float64
 15  sjit               175341 non-null  float64
 16  djit               175341 non-null  float64
 17  swin               175341 non-null  int64
 18  stcpb              175341 non-null  int64
 19  dtcpb              175341 non-null  int64
 20  dwin               175341 non-null  int64
 21  tcprtt             175341 non-null  float64
 22  synack             175341 non-null  float64
 23  ackdat             175341 non-null  float64
 24  smean              175341 non-null  int64
 25  dmean              175341 non-null  int64
 26  trans_depth        175341 non-null  int64
 27  response_body_len  175341 non-null  int64
 28  ct_src_dport_ltm   175341 non-null  int64
 29  ct_dst_sport_ltm   175341 non-null  int64
 30  is_ftp_login       175341 non-null  int64
 31  ct_ftp_cmd         175341 non-null  int64
 32  ct_flw_http_mthd   175341 non-null  int64
 33  is_sm_ips_ports    175341 non-null  int64
 34  attack_cat         175341 non-null  object
 35  label              175341 non-null  int64
dtypes: float64(11), int64(21), object(4)
memory usage: 48.2+ MB

In [22]:
# 3
df.isna().sum()

dur                  0
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
is_sm_ips_ports      0
attack_cat           0
label                0
dtype: int64

In [23]:
# 4
df[['sbytes', 'dbytes', 'dur']].describe()

             sbytes        dbytes            dur
count  1.753410e+05  1.753410e+05  175341.000000
mean   8.844844e+03  1.492892e+04       1.359389
std    1.747656e+05  1.436542e+05       6.480249
min    2.800000e+01  0.000000e+00       0.000000
25%    1.140000e+02  0.000000e+00       0.000008
50%    4.300000e+02  1.640000e+02       0.001582
75%    1.418000e+03  1.102000e+03       0.668069
max    1.296523e+07  1.465555e+07      59.999990

In [24]:
# 5 and 6
df.nunique()
#df.nunique()/len(df)

df = df.drop_duplicates()
df.shape

(96822, 36)

In [25]:
#7

neww_df = df[df['label'] != 1]

# 8
new_df = df[df['sbytes'] > 10000]
df.shape

(96822, 36)

In [26]:
df['sbytes'].describe()

count    9.682200e+04
mean     1.534994e+04
std      2.348021e+05
min      2.800000e+01
25%      5.640000e+02
50%      1.048000e+03
75%      2.958000e+03
max      1.296523e+07
Name: sbytes, dtype: float64

In [27]:
# 9
df['HighByteTraffic'] = df['sbytes'].apply(lambda x: 'High' if x > 10000 else 'Low')
df.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label,HighByteTraffic
0,0.121478,tcp,-,FIN,6,4,258,172,74.087490,14158.9420,...,0,1,1,0,0,0,0,Normal,0,Low
1,0.649902,tcp,-,FIN,14,38,734,42014,78.473370,8395.1120,...,0,1,1,0,0,0,0,Normal,0,Low
2,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,1572.2719,...,0,1,1,0,0,0,0,Normal,0,Low
3,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,2740.1790,...,0,1,1,1,1,0,0,Normal,0,Low
4,0.449454,tcp,-,FIN,10,6,534,268,33.373825,8561.4990,...,0,2,1,0,0,0,0,Normal,0,Low

In [ ]:
# 10
df[['sbytes', 'dbytes', 'dur', 'label']].groupby('label').mean()

             sbytes        dbytes       dur
label
0       4608.542009  35183.041437  0.980252
1      26307.836546  17444.076239  2.016045

In [ ]:

# 11
df['TrafficRatio'] = df['sbytes']/df['dbytes']
df[['sbytes', 'dbytes', 'TrafficRatio']].head()

   sbytes  dbytes  TrafficRatio
0     258     172      1.500000
1     734   42014      0.017470
2     364   13186      0.027605
3     628     770      0.815584
4     534     268      1.992537

In [ ]:
#12
df[['sbytes', 'dbytes', 'dur', 'proto']].groupby('proto').mean()

           sbytes  dbytes       dur
proto
3pc         200.0     0.0  0.000006
a/n         200.0     0.0  0.000006
aes-sp3-d   200.0     0.0  0.000007
any         200.0     0.0  0.000007
argus       180.0     0.0  0.000009
...           ...     ...       ...
wsn         200.0     0.0  0.000006
xnet        180.0     0.0  0.000003
xns-idp     200.0     0.0  0.000007
xtp         200.0     0.0  0.000006
zero        200.0     0.0  0.000006

[133 rows x 3 columns]